$expect('#side > a').to.have.css('display', 'block', "Did you set the display of #side > a to block?");
$expect('#side > a').to.have.css('width', '40px', "Did you set the width of #side > a to 40px?");
$expect('#side > a').to.have.css('height', '40px', "Did you set the height of #side > a to 40px?");
$expect('#side > a').to.have.css('border-radius', '10px', "Did you set the border-radius of #side > a to 10px?");
$expect('#side > a').to.have.css('float', 'right', "Did you set the float of #side > a to right?");
$expect('#side > a').to.have.css('color', 'black', "Did you set the color of #side > a to black?");
$expect('#side > a').to.have.css('text-align', 'center', "Did you set the text-align of #side > a to center?");
$expect('#side > a').to.have.css('font-size', '32px', "Did you set the font-size of #side > a to 32px?");
$expect('#side > a').to.have.css('padding', '10px 10px 10px 10px', "Did you set the padding of #side > a to 10px?");
$expect('#side > a').to.have.css('margin', '5px 5px 5px 5px', "Did you set the margin of #side > a to 5px?");
$expect('#side > a').to.have.css('cursor', 'pointer', "Did you set the cursor of #side > a to pointer?");